// Generated by scripts/generate-recipe.mjs; edit recipe-descriptor.mjs.
export type Mapping = {
  readonly control: string;
  readonly range: readonly [number, number];
  readonly scale: "linear" | "exponential";
};
export type Variation = { readonly random: readonly [number, number] };
export type PointValue = number | Mapping | Variation;
export type Value =
  | PointValue
  | {
      readonly points: ReadonlyArray<readonly [number, PointValue]>;
      readonly curve: "linear" | "exponential";
    };
export type Frequency = Value;
export type Parameter =
  | {
      readonly min: number;
      readonly max: number;
      readonly default: number;
      readonly mode: "play";
    }
  | {
      readonly min: number;
      readonly max: number;
      readonly default: number;
      readonly mode: "live";
      readonly smoothing: number;
    };
export type Parameters = Readonly<Record<string, Parameter>>;
export type Envelope = {
  readonly attack: number;
  readonly decay: number;
  readonly sustain: number;
  readonly release: number;
};
export type Filter = {
  readonly type: "filter";
  readonly filter: "lowpass" | "highpass" | "bandpass";
  readonly frequency: Frequency;
  readonly q: number;
};
export type Source =
  | {
      readonly type: "oscillator";
      readonly waveform: "sine" | "triangle" | "sawtooth" | "square";
      readonly frequency: Frequency;
    }
  | { readonly type: "noise"; readonly color: "white" };
export type Layer = {
  readonly id: string;
  readonly source: Source;
  readonly gainDb: PointValue;
  readonly envelope: Envelope;
  readonly effects?: ReadonlyArray<Filter>;
};
export type OneShotRecipe = {
  readonly schemaVersion: 1;
  readonly kind: "one-shot";
  readonly duration: number;
  readonly parameters?: Parameters;
  readonly layers: ReadonlyArray<Layer>;
  readonly effects?: ReadonlyArray<Filter>;
};
export type SustainedRecipe = {
  readonly schemaVersion: 1;
  readonly kind: "sustained";
  readonly parameters?: Parameters;
  readonly layers: ReadonlyArray<Layer>;
  readonly effects?: ReadonlyArray<Filter>;
};
export type Recipe = OneShotRecipe | SustainedRecipe;
function freeze(value: unknown): void {
  if (value && typeof value === "object") {
    for (const child of Object.values(value)) freeze(child);
    Object.freeze(value);
  }
}
export const recipeSchema: Readonly<Record<string, unknown>> = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $ref: "#/$defs/Recipe",
  $defs: {
    Mapping: {
      type: "object",
      properties: {
        control: { type: "string", minLength: 1, maxLength: 64 },
        range: {
          type: "array",
          prefixItems: [
            { type: "number", minimum: -60000, maximum: 60000 },
            { type: "number", minimum: -60000, maximum: 60000 },
          ],
          minItems: 2,
          maxItems: 2,
        },
        scale: { enum: ["linear", "exponential"] },
      },
      required: ["control", "range", "scale"],
      additionalProperties: false,
    },
    Variation: {
      type: "object",
      properties: {
        random: {
          type: "array",
          prefixItems: [
            { type: "number", minimum: -60000, maximum: 60000 },
            { type: "number", minimum: -60000, maximum: 60000 },
          ],
          minItems: 2,
          maxItems: 2,
        },
      },
      required: ["random"],
      additionalProperties: false,
    },
    PointValue: {
      anyOf: [
        { type: "number", minimum: -60000, maximum: 60000 },
        { $ref: "#/$defs/Mapping" },
        { $ref: "#/$defs/Variation" },
      ],
    },
    Value: {
      anyOf: [
        { $ref: "#/$defs/PointValue" },
        {
          type: "object",
          properties: {
            points: {
              type: "array",
              items: {
                type: "array",
                prefixItems: [
                  { type: "number", minimum: 0, maximum: 60 },
                  { $ref: "#/$defs/PointValue" },
                ],
                minItems: 2,
                maxItems: 2,
              },
              minItems: 1,
              maxItems: 128,
            },
            curve: { enum: ["linear", "exponential"] },
          },
          required: ["points", "curve"],
          additionalProperties: false,
        },
      ],
    },
    Frequency: { $ref: "#/$defs/Value" },
    Parameter: {
      anyOf: [
        {
          type: "object",
          properties: {
            min: { type: "number", minimum: -60000, maximum: 60000 },
            max: { type: "number", minimum: -60000, maximum: 60000 },
            default: { type: "number", minimum: -60000, maximum: 60000 },
            mode: { const: "play" },
          },
          required: ["min", "max", "default", "mode"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: {
            min: { type: "number", minimum: -60000, maximum: 60000 },
            max: { type: "number", minimum: -60000, maximum: 60000 },
            default: { type: "number", minimum: -60000, maximum: 60000 },
            mode: { const: "live" },
            smoothing: { type: "number", minimum: 0.005, maximum: 1 },
          },
          required: ["min", "max", "default", "mode", "smoothing"],
          additionalProperties: false,
        },
      ],
    },
    Parameters: {
      type: "object",
      maxProperties: 16,
      propertyNames: { pattern: "^[A-Za-z][A-Za-z0-9_]{0,63}$" },
      additionalProperties: { $ref: "#/$defs/Parameter" },
    },
    Envelope: {
      type: "object",
      properties: {
        attack: { type: "number", minimum: 0, maximum: 10 },
        decay: { type: "number", minimum: 0, maximum: 10 },
        sustain: { type: "number", minimum: 0, maximum: 1 },
        release: { type: "number", minimum: 0.005, maximum: 10 },
      },
      required: ["attack", "decay", "sustain", "release"],
      additionalProperties: false,
    },
    Filter: {
      type: "object",
      properties: {
        type: { const: "filter" },
        filter: { enum: ["lowpass", "highpass", "bandpass"] },
        frequency: { $ref: "#/$defs/Frequency" },
        q: { type: "number", minimum: 0.1, maximum: 20 },
      },
      required: ["type", "filter", "frequency", "q"],
      additionalProperties: false,
    },
    Source: {
      anyOf: [
        {
          type: "object",
          properties: {
            type: { const: "oscillator" },
            waveform: { enum: ["sine", "triangle", "sawtooth", "square"] },
            frequency: { $ref: "#/$defs/Frequency" },
          },
          required: ["type", "waveform", "frequency"],
          additionalProperties: false,
        },
        {
          type: "object",
          properties: { type: { const: "noise" }, color: { const: "white" } },
          required: ["type", "color"],
          additionalProperties: false,
        },
      ],
    },
    Layer: {
      type: "object",
      properties: {
        id: { type: "string", minLength: 1, maxLength: 64 },
        source: { $ref: "#/$defs/Source" },
        gainDb: { $ref: "#/$defs/PointValue" },
        envelope: { $ref: "#/$defs/Envelope" },
        effects: {
          type: "array",
          items: { $ref: "#/$defs/Filter" },
          minItems: 0,
          maxItems: 8,
        },
      },
      required: ["id", "source", "gainDb", "envelope"],
      additionalProperties: false,
    },
    OneShotRecipe: {
      type: "object",
      properties: {
        schemaVersion: { const: 1 },
        kind: { const: "one-shot" },
        duration: {
          type: "number",
          minimum: 0,
          maximum: 60,
          exclusiveMinimum: 0,
        },
        parameters: { $ref: "#/$defs/Parameters" },
        layers: {
          type: "array",
          items: { $ref: "#/$defs/Layer" },
          minItems: 1,
          maxItems: 16,
        },
        effects: {
          type: "array",
          items: { $ref: "#/$defs/Filter" },
          minItems: 0,
          maxItems: 8,
        },
      },
      required: ["schemaVersion", "kind", "duration", "layers"],
      additionalProperties: false,
    },
    SustainedRecipe: {
      type: "object",
      properties: {
        schemaVersion: { const: 1 },
        kind: { const: "sustained" },
        parameters: { $ref: "#/$defs/Parameters" },
        layers: {
          type: "array",
          items: { $ref: "#/$defs/Layer" },
          minItems: 1,
          maxItems: 16,
        },
        effects: {
          type: "array",
          items: { $ref: "#/$defs/Filter" },
          minItems: 0,
          maxItems: 8,
        },
      },
      required: ["schemaVersion", "kind", "layers"],
      additionalProperties: false,
    },
    Recipe: {
      anyOf: [
        { $ref: "#/$defs/OneShotRecipe" },
        { $ref: "#/$defs/SustainedRecipe" },
      ],
    },
  },
};
freeze(recipeSchema);
