import { readFile, writeFile } from "node:fs/promises";
import { descriptor } from "./recipe-descriptor.mjs";
import prettier from "prettier";

function type(node) {
  if (node.$ref) return node.$ref.split("/").at(-1);
  if ("const" in node) return JSON.stringify(node.const);
  if (node.enum)
    return node.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (node.anyOf) return node.anyOf.map(type).join(" | ");
  if (node.type === "number") return "number";
  if (node.type === "string") return "string";
  if (node.prefixItems)
    return `readonly [${node.prefixItems.map(type).join(", ")}]`;
  if (node.type === "array") return `ReadonlyArray<${type(node.items)}>`;
  if (!node.properties)
    return `Readonly<Record<string, ${type(node.additionalProperties)}>>`;
  return `{ ${Object.entries(node.properties)
    .map(
      ([key, value]) =>
        `readonly ${key}${node.required.includes(key) ? "" : "?"}: ${type(value)};`,
    )
    .join(" ")} }`;
}
const manifest = JSON.parse(
  await readFile(
    new URL("../packages/audiobits/package.json", import.meta.url),
    "utf8",
  ),
);
const definitions = descriptor.$defs;
const capabilities = {
  packageVersion: manifest.version,
  schemaVersion: definitions.OneShotRecipe.properties.schemaVersion.const,
  status: manifest.private ? "unreleased" : "development",
  recipe: {
    kinds: definitions.Recipe.anyOf.map(
      (node) => definitions[node.$ref.split("/").at(-1)].properties.kind.const,
    ),
    sources: definitions.Source.anyOf.map((node) => node.properties.type.const),
    waveforms: definitions.Source.anyOf[0].properties.waveform.enum,
    noiseColors: [definitions.Source.anyOf[1].properties.color.const],
    filters: definitions.Filter.properties.filter.enum,
    parameterModes: definitions.Parameter.anyOf.map(
      (node) => node.properties.mode.const,
    ),
    mappingScales: definitions.Mapping.properties.scale.enum,
    automationCurves: definitions.Value.anyOf[1].properties.curve.enum,
    values: ["number", "mapping", "seeded-variation", "frequency-automation"],
  },
  curatedRecipes: [
    "confirmation",
    "impact",
    "thruster",
    "tactileClick",
    "gentleRejection",
    "glassNotification",
    "whoosh",
    "powerUp",
  ],
  runtime: [
    "gesture-start",
    "bounded-voices",
    "live-controls",
    "seeded-replay",
    "buses",
    "native-output-tap",
    "suspend",
    "dispose",
  ],
  experimentalRuntime: [],
  browserGate: "Chromium",
  browserMatrix: ["Chromium"],
  schemaNote:
    "Structural schema only; validateRecipe also enforces semantic and resource limits. Playback checks context sample rate.",
};
const files = {
  "packages/audiobits/src/recipe/capabilities.json":
    JSON.stringify(capabilities),
  "packages/audiobits/src/recipe/generated.ts": `// Generated by scripts/generate-recipe.mjs; edit recipe-descriptor.mjs.\n${Object.entries(
    descriptor.$defs,
  )
    .map(([name, node]) => `export type ${name} = ${type(node)};`)
    .join(
      "\n",
    )}\nfunction freeze(value: unknown): void { if (value && typeof value === "object") { for (const child of Object.values(value)) freeze(child); Object.freeze(value); } }
export const recipeSchema: Readonly<Record<string, unknown>> = ${JSON.stringify(descriptor)};
freeze(recipeSchema);\n`,
  "packages/audiobits/src/recipe/schema.json": JSON.stringify(descriptor),
};
for (const [path, source] of Object.entries(files)) {
  const formatted = await prettier.format(source, { filepath: path });
  const target = new URL(`../${path}`, import.meta.url);
  if (process.argv.includes("--check")) {
    if ((await readFile(target, "utf8")) !== formatted)
      throw new Error(`Stale generated recipe artifact: ${path}`);
  } else await writeFile(target, formatted);
}
